### ISSUE TITLE
Avoid using `sudo`

### ISSUE THREAD

**Issue by sftim** [fuzz/crossplane-setup#1]
https://github.com/fuzz/crossplane-setup/blob/64f468e41fe758deba871a27246bc654d2ce0c0f/crossplane-setup.sh#L38-L45 runs `snap` with `sudo`.

However, the script doesn't know what the sudo setup is on that computer.

How I'd write it:
- generate a list of missing tools
- print a hint that the system may prompt for privileges to install that list of tools (and list which tools will be unconfined)

- and then install them in at most two goes:
  - `snap install docker`
  - print note about unconfined tool (`kubectl`, `helm`)
  - `snap install --classic kubectl helm`

`snap` can then use PolicyKit to get more privilege if needed.

**Comment by fuzz** [comment]
Thanks! I'm new to Snap this week :) Apple stopped supporting my 2013 MBP so I went Ubuntu. I'll work on this.

**Comment by fuzz** [comment]
In retrospect I wish it would have occurred to me to try running `snap install --classic kubectl helm` before rewriting the script to support it as it doesn't actually work:
```
error: cannot specify mode for multiple store snaps (only for one store snap or several local ones)
```
I'll merge in the warning about unconfined and light the rest of the `snapper` branch on fire.

**Comment by sftim** [comment]
> In retrospect I wish it would have occurred to me to try running `snap install --classic kubectl helm` before rewriting the script to support it as it doesn't actually work.

Oops, sorry.

**Comment by fuzz** [comment]
No worries! It was a good suggestion--it's no fun typing your password three times in a row. The other info about Snap was very helpful :)
